/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.Automovel;
import java.awt.Component;
import java.util.Enumeration;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JPanel;

/**
 *
 * @author alunoces
 */
public class FormPrincipal extends javax.swing.JFrame {

    Automovel auto;
    
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbPlaca = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        lbModelo = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        lbDataFabricacao = new javax.swing.JLabel();
        tfDataFabricacao = new javax.swing.JTextField();
        lbMotor = new javax.swing.JLabel();
        cbMotor = new javax.swing.JComboBox<>();
        lbValorBasico = new javax.swing.JLabel();
        tfValorBasico = new javax.swing.JTextField();
        pnCategoria = new javax.swing.JPanel();
        rbPasseio = new javax.swing.JRadioButton();
        rbUtilitario = new javax.swing.JRadioButton();
        rbCarga = new javax.swing.JRadioButton();
        lbAliquotaImposto = new javax.swing.JLabel();
        tfAliquotaImposto = new javax.swing.JTextField();
        btCalculoValorTotal = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbImpostoPagar = new javax.swing.JLabel();
        tfImpostoPagar = new javax.swing.JTextField();
        lbValorTotalCompra = new javax.swing.JLabel();
        tfValorTotalCompra = new javax.swing.JTextField();
        lbDadosAutomovel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDadosAutomovel = new javax.swing.JTextArea();
        btExibir = new javax.swing.JButton();
        lbMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Automóveis");
        setBackground(new java.awt.Color(255, 204, 204));
        setResizable(false);

        lbPlaca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPlaca.setText("Placa");
        lbPlaca.setName("lbPlaca"); // NOI18N

        tfPlaca.setBackground(new java.awt.Color(0, 0, 102));
        tfPlaca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfPlaca.setForeground(new java.awt.Color(255, 255, 0));
        tfPlaca.setToolTipText("Digite a placa");
        tfPlaca.setName("tfPlaca"); // NOI18N

        lbModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbModelo.setText("Modelo");
        lbModelo.setName("lbModelo"); // NOI18N

        tfModelo.setName("tfModelo"); // NOI18N

        btAdicionar.setBackground(new java.awt.Color(102, 153, 255));
        btAdicionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.setName("btAdicionar"); // NOI18N
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        lbDataFabricacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDataFabricacao.setText("Data de Fabricação");
        lbDataFabricacao.setName("lbDataFabricacao"); // NOI18N

        tfDataFabricacao.setName("tfDataFabricacao"); // NOI18N

        lbMotor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMotor.setText("Motorização");
        lbMotor.setName("lbMotor"); // NOI18N

        cbMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.2", "2.3", "4.2", "4.3" }));
        cbMotor.setName("cbMotor"); // NOI18N

        lbValorBasico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValorBasico.setText("Valor básico");
        lbValorBasico.setName("lbValorBasico"); // NOI18N

        tfValorBasico.setName("tfValorBasico"); // NOI18N

        pnCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnCategoria.setName(""); // NOI18N

        buttonGroup1.add(rbPasseio);
        rbPasseio.setText("Passeio");
        rbPasseio.setName("rbPasseio"); // NOI18N

        buttonGroup1.add(rbUtilitario);
        rbUtilitario.setText("Utilitário");
        rbUtilitario.setName("rbUtilitario"); // NOI18N

        buttonGroup1.add(rbCarga);
        rbCarga.setText("Carga");
        rbCarga.setName("rbCarga"); // NOI18N

        javax.swing.GroupLayout pnCategoriaLayout = new javax.swing.GroupLayout(pnCategoria);
        pnCategoria.setLayout(pnCategoriaLayout);
        pnCategoriaLayout.setHorizontalGroup(
            pnCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCategoriaLayout.createSequentialGroup()
                .addComponent(rbPasseio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbUtilitario)
                .addGap(79, 79, 79)
                .addComponent(rbCarga))
        );
        pnCategoriaLayout.setVerticalGroup(
            pnCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCategoriaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPasseio)
                    .addComponent(rbUtilitario)
                    .addComponent(rbCarga))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lbAliquotaImposto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAliquotaImposto.setText("Aliquota de Imposto");
        lbAliquotaImposto.setName("lbAliquotaImposto"); // NOI18N

        tfAliquotaImposto.setName("tfAliquotaImposto"); // NOI18N

        btCalculoValorTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCalculoValorTotal.setText("Calcular Valor Total");
        btCalculoValorTotal.setName("btCalculoValorTotal"); // NOI18N
        btCalculoValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculoValorTotalActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 0, 0));
        btLimpar.setText("Limpar");
        btLimpar.setName("btLimpar"); // NOI18N
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbImpostoPagar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbImpostoPagar.setText("Imposto a Pagar");
        lbImpostoPagar.setName("lbImpostoPagar"); // NOI18N

        tfImpostoPagar.setEditable(false);
        tfImpostoPagar.setBackground(new java.awt.Color(204, 204, 204));
        tfImpostoPagar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), null));
        tfImpostoPagar.setName("tfImpostoPagar"); // NOI18N

        lbValorTotalCompra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValorTotalCompra.setText("Valor total de compra");
        lbValorTotalCompra.setName("lbValorTotalCompra"); // NOI18N

        tfValorTotalCompra.setEditable(false);
        tfValorTotalCompra.setBackground(new java.awt.Color(204, 204, 204));
        tfValorTotalCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), null));
        tfValorTotalCompra.setName("tfValorTotalCompra"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tfImpostoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbImpostoPagar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbValorTotalCompra)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tfValorTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImpostoPagar)
                    .addComponent(lbValorTotalCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfImpostoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfValorTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbDadosAutomovel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDadosAutomovel.setText("Dados do Automóvel");
        lbDadosAutomovel.setName("lbDadosAutomovel"); // NOI18N

        jScrollPane1.setForeground(new java.awt.Color(51, 51, 255));

        taDadosAutomovel.setColumns(20);
        taDadosAutomovel.setRows(5);
        taDadosAutomovel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        taDadosAutomovel.setName("taDadosAutomovel"); // NOI18N
        jScrollPane1.setViewportView(taDadosAutomovel);

        btExibir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExibir.setText("Exibir");
        btExibir.setName("btExibir"); // NOI18N
        btExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExibirActionPerformed(evt);
            }
        });

        lbMensagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMensagem.setForeground(new java.awt.Color(0, 51, 255));
        lbMensagem.setName("lbMensagem"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btExibir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbPlaca)
                                    .addGap(46, 46, 46)
                                    .addComponent(lbModelo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbAliquotaImposto)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(tfAliquotaImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addComponent(btCalculoValorTotal)
                                        .addGap(26, 26, 26)
                                        .addComponent(btLimpar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btAdicionar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbMotor)
                                            .addComponent(cbMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbValorBasico)
                                            .addComponent(tfValorBasico)))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbMensagem)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbDadosAutomovel)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPlaca)
                    .addComponent(lbModelo))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAdicionar)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataFabricacao)
                    .addComponent(lbMotor)
                    .addComponent(lbValorBasico))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfValorBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAliquotaImposto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfAliquotaImposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btCalculoValorTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lbMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lbDadosAutomovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExibir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
        );

        setSize(new java.awt.Dimension(439, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        auto = new Automovel();
        
        auto.setPlaca(tfPlaca.getText());
        auto.setModelo(tfModelo.getText());
        auto.setDataFabricacao(tfDataFabricacao.getText());
        auto.setValorBasico(Float.parseFloat(tfValorBasico.getText()));
        auto.setMotor(cbMotor.getSelectedItem().toString());
        
        JRadioButton radio;
        Enumeration jr = buttonGroup1.getElements();
        while(jr.hasMoreElements())
        {
            radio = (JRadioButton)jr.nextElement();
            if(radio.isSelected())
            {
                auto.setCategoria(radio.getText());
            }
        }
        lbMensagem.setText("Automóvel cadastrado com sucesso!");
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExibirActionPerformed
        taDadosAutomovel.setText(auto.toString());
    }//GEN-LAST:event_btExibirActionPerformed

    private void btCalculoValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculoValorTotalActionPerformed
        int aliq = Integer.parseInt(tfAliquotaImposto.getText());
         float imposto;
         float total;
         
         //fazendo os calculos necessários
         imposto = auto.calcularImposto(aliq);
         total = auto.valorTotalVeiculo(aliq);
         
         //colocando nos campos na interface
         tfImpostoPagar.setText(Float.toString(imposto));
         tfValorTotalCompra.setText(Float.toString(total));
    }//GEN-LAST:event_btCalculoValorTotalActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        buttonGroup1.clearSelection();
        cbMotor.setSelectedIndex(-1);
        taDadosAutomovel.setText("");
        
        for(int i=0; i<getContentPane().getComponentCount(); i++)
        {
            Component c = getContentPane().getComponent(i);
            if(c instanceof JTextField)
            {
                JTextField field = (JTextField)c;
                field.setText("");
            }
            if(c instanceof JPanel)
            {
                JPanel p = (JPanel)c;
                for(int j=0; j<p.getComponentCount(); j++)
                {
                    Component c2 = p.getComponent(j);
                    if(c2 instanceof JTextField)
                    {
                        JTextField field = (JTextField)c2;
                        field.setText("");
                    }
                }
            }
        }
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCalculoValorTotal;
    private javax.swing.JButton btExibir;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbMotor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAliquotaImposto;
    private javax.swing.JLabel lbDadosAutomovel;
    private javax.swing.JLabel lbDataFabricacao;
    private javax.swing.JLabel lbImpostoPagar;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbMotor;
    private javax.swing.JLabel lbPlaca;
    private javax.swing.JLabel lbValorBasico;
    private javax.swing.JLabel lbValorTotalCompra;
    private javax.swing.JPanel pnCategoria;
    private javax.swing.JRadioButton rbCarga;
    private javax.swing.JRadioButton rbPasseio;
    private javax.swing.JRadioButton rbUtilitario;
    private javax.swing.JTextArea taDadosAutomovel;
    private javax.swing.JTextField tfAliquotaImposto;
    private javax.swing.JTextField tfDataFabricacao;
    private javax.swing.JTextField tfImpostoPagar;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTextField tfValorBasico;
    private javax.swing.JTextField tfValorTotalCompra;
    // End of variables declaration//GEN-END:variables
}
